name: Run Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Set up .env.local
        run: |
          echo "NODE_ENV=local" >> .env.local
          echo "PRIVATE_RSA_KEY=mock_private_key" >> .env.local
          echo "PUBLIC_RSA_KEY=mock_public_key" >> .env.local
          echo "EMAIL_USERNAME=test@example.com" >> .env.local
          echo "EMAIL_PASSWORD=password" >> .env.local
          echo "EMAIL_HOST=smtp.example.com" >> .env.local
          echo "EMAIL_PORT=25" >> .env.local

      - name: Execute unit tests
        run: pnpm tests:unit
